//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gapura.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departement
    {
        public int DepartemenID { get; set; }
        public string DepartemenName { get; set; }
        public int DivisionID { get; set; }
        public string Note { get; set; }
    
        public virtual Division Division { get; set; }
    }
}
