//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gapura.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterPeriod
    {
        public int PeriodID { get; set; }
        public System.DateTime StartPeriod { get; set; }
        public System.DateTime EndPeriod { get; set; }
        public string PeriodName { get; set; }
        public Nullable<bool> ClosePeriod { get; set; }
    }
}
