//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gapura.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleaseHeader
    {
        public int ReleaseID { get; set; }
        public int RequestID { get; set; }
        public string ReleaseNo { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> TotalRequest { get; set; }
        public Nullable<int> TotalRelease { get; set; }
        public string ReleaseNote { get; set; }
        public string UserID { get; set; }
        public Nullable<int> DepartemenID { get; set; }
    }
}
