//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gapura.BLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCard
    {
        public int TransactionID { get; set; }
        public string TransactionNo { get; set; }
        public string TransCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public int ProductID { get; set; }
        public string Note { get; set; }
        public Nullable<long> TransactionIN { get; set; }
        public Nullable<long> TransactionOUT { get; set; }
        public int DepartemenID { get; set; }
    }
}
